<a href="https://colab.research.google.com/github/mehektamboli/python/blob/main/practical_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

A = np.array([[4, 2],
              [3, 5]])

rank = np.linalg.matrix_rank(A)

determinant = np.linalg.det(A)

transpose = np.transpose(A)

inverse = np.linalg.inv(A)

eigenvalues, eigenvectors = np.linalg.eig(A)

print("Matrix A:\n", A)
print("\nRank of A:", rank)
print("Determinant of A:", determinant)
print("Transpose of A:\n", transpose)
print("Inverse of A:\n", inverse)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

arr = np.array([5, 2, 9, 1, 7, 3])

max_element = np.max(arr)
min_element = np.min(arr)

print("Array:", arr)
print("Maximum element:", max_element)
print("Minimum element:", min_element)

sorted_arr = np.sort(arr)
print("Sorted array:", sorted_arr)

mean_value = np.mean(arr)
print("Mean of array:", mean_value)

A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])


result = np.dot(A, B)

print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Product of A and B:\n", result)


Matrix A:
 [[4 2]
 [3 5]]

Rank of A: 2
Determinant of A: 14.000000000000004
Transpose of A:
 [[4 3]
 [2 5]]
Inverse of A:
 [[ 0.35714286 -0.14285714]
 [-0.21428571  0.28571429]]
Eigenvalues: [2. 7.]
Eigenvectors:
 [[-0.70710678 -0.5547002 ]
 [ 0.70710678 -0.83205029]]
Array: [5 2 9 1 7 3]
Maximum element: 9
Minimum element: 1
Sorted array: [1 2 3 5 7 9]
Mean of array: 4.5
Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
Product of A and B:
 [[19 22]
 [43 50]]
